<?php

register_uninstall_hook(__FILE__, 'wbslide_remove_meta_data_from_posts');

add_action('add_meta_boxes', 'wbslide_add_slide_meta_box');
add_action('save_post', 'wbslide_save_post', 10, 2);

/**
 * Creates meta box for slide switch
 */
function wbslide_add_slide_meta_box() {
  add_meta_box(
    'wbslide_slide_box',
    __('WB-slide', 'wb-slide'),
    'wbslide_slide_meta_box',
    'post',
    'side',
    'default'
  );
}

/**
 * Saves post's slide meta field
 */
function wbslide_save_post($post_id, $post) {
  if(!isset($_POST['wbslide_slide_nonce']) || !wp_verify_nonce($_POST['wbslide_slide_nonce'], basename( __FILE__ )))
    return $post_id;

  if(defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) 
    return $post_id;

  $post_type = get_post_type_object($post->post_type);
  if(!current_user_can($post_type->cap->edit_post, $post_id))
    return $post_id;

  $meta_key = '_wbslide_slide';

  $meta_value = get_post_meta($post_id, $meta_key, true);
  $new_meta_value = isset($_POST['wbslide-slide']) ? "1" : "0"; //if isset, checkbox is checked

  update_post_meta($post_id, $meta_key, $new_meta_value);
}


/**
 * Echoes custom meta box with slide checkbox
 */
function wbslide_slide_meta_box($post) {
  wp_nonce_field(basename(__FILE__), 'wbslide_slide_nonce');
  $checked = get_post_meta($post->ID, '_wbslide_slide', true);

  include('tpl/meta_box.php');
}

/**
 * Removes all metadata generated by the plugin
 */
function wbslide_remove_meta_data_from_posts() {
  delete_metadata('post', 0, 'wbslide_slide', '', true);
}
